# Generated by Django 4.0.2 on 2022-04-29 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('life', models.IntegerField()),
                ('max_life', models.IntegerField()),
                ('power', models.IntegerField()),
                ('max_power', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('max_agility', models.IntegerField()),
                ('block', models.IntegerField()),
                ('max_block', models.IntegerField()),
                ('block_factor', models.IntegerField(default=0)),
                ('energy', models.IntegerField()),
                ('max_energy', models.IntegerField()),
                ('rarity', models.TextField()),
                ('wins', models.IntegerField(default=0)),
                ('ko', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('injury', models.TextField(default='none')),
                ('average', models.IntegerField()),
                ('coins', models.IntegerField(default=0)),
                ('hexed_instance', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
