# Generated by Django 4.0.2 on 2022-05-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightermodel',
            name='injury',
        ),
    ]
