# Generated by Django 4.0.2 on 2022-04-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_fightermodel_block_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fightermodel',
            old_name='max_speed',
            new_name='agility',
        ),
        migrations.RenameField(
            model_name='fightermodel',
            old_name='speed',
            new_name='max_agility',
        ),
    ]
