# Generated by Django 4.0.2 on 2022-05-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_fightermodel_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightermodel',
            name='injury',
        ),
    ]
