# Generated by Django 4.0.2 on 2022-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_max_speed_fightermodel_agility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightermodel',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
