# Generated by Django 4.0.2 on 2022-03-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import noter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('deadline', models.DateField(default=noter.models.Note.create_now)),
                ('is_done', models.BooleanField(default=False)),
                ('created', models.DateField(default=noter.models.Note.create_now, editable=False)),
                ('modified', models.DateField(default=noter.models.Note.create_now)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
